import "./globals.css";
import MenuBar from "@/components/MenuBar";
import TextInput from "@/components/TextInput";

export const metadata = {
  title: "ChatGPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-safe-h-screen flex flex-col bg-base-300">
        <MenuBar />
        <div className="flex-grow" />
        <main className="">{children}</main>
        <TextInput />
      </body>
    </html>
  );
}
